/**
 * Land / ocean mask used by the dotted globe.
 *
 * 360 x 180 cells (1 degree each), row-major from the north-west corner
 * (lon -180, lat 90). One bit per cell, least-significant bit first,
 * base64 encoded (about 8 KB decoded).
 *
 * Generated from Natural Earth 1:50m land polygons (public domain) via the
 * `world-atlas` package, then rasterised with 4x supersampling per cell.
 */
export const LAND_MASK_WIDTH = 360;
export const LAND_MASK_HEIGHT = 180;

export const LAND_MASK_B64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADI/wMAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/P8/IMz//z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD+//+H" +
  "//////9/AAAAAAAAAABwAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAPD//3/+//////8fAAAAABEAAHg7CwAAAD8AAAAAAAAAAAAA" +
  "AAAAAAAAAAAAGPD//wv4//////8DAACA9z4AAAAAAAAAAP0EAAAAAAAAAAAAAAAAAAAAAAAA4Iz///H//////38AAAAA/wMAAAAA" +
  "AAAAAAAfAAAAAAAAAAAAAAAAAAAAAOA4QDDwP8D///////8BAAAAOBwAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAPzHQPv/P4D/" +
  "/////38AAAAAEAAAAAAA+gEAABD/DwAAAAAAAAAAAAAAAAAAAKD/yzP/DwAA/v////8DAAAAAAAAAADgDwAA4P//PwAA4N8AAAAA" +
  "AAAAAAAAAA8cACD/DgAA+P////8AAAAAAAAAAAD4AAAA/P//HwAAAAAAAAAAAAAAAAAAAP8ChOf5fwAA8P///38AAAAAAAAAAAAc" +
  "AATg/////wMPAAYAAAAAAAAAAAAAgN9/h6e8twEA8P///z8AAAAAAAAAAAAPAJ7s//////8fgO8BAAAAAwCAAAAAAOf/D3b8/x8A" +
  "4P///z8AAAAAAAAAAAAPgP////////8/3/8HAACAAAD4/wAAAMD/P/j4/38A4P///zcAAAAAAPwHAAAYgN//////////////DwAA" +
  "AAD+//9x/5//f+7Bg/8B4P7//w8AAAAA4P8/ACAAn9///////////////59/A8D///////95Bs7Pg/0BAP7//wMAAAAA/P//B4P7" +
  "/9//////////////////HwD////////////vg/EfwP//BwAAAAAA+P//H/P//9///////////////////8P8////////////A/w/" +
  "gP//AyAQAAAA/v//X////////////////////////eH////////////fgP8ZgP8/AOA/AAAA/uN/8P//////////////////////" +
  "QMD7///////////vw/0HAP8PAMA/AACA//H//v////////////////////9/AAT8///////////jBPAHAP4HAAADAADw//z/////" +
  "//////////////////9/AID//////////38Aw4UDAPwDAAAAAAD8P/7///////////////////////9fAMD//////////z8AwA8A" +
  "APgDAAAAAAD+H/7/////////////////////cf8DAKD///3//////z8AwH8AAMABAAAAAAD+P/z/////////////////////wH8A" +
  "AAD8N4D+/////x8AwH8MAAAAAAAAAAD+f/D///////////////////9/cAAAAADACwD0/////38AwP8fAAAAAAAAgACcH/D/////" +
  "/////////////wMAOAAAAADABADw//////8AgP8/AAAAAAAAwAMAX/T//////////////////wAAfgAAAAAwAACg//////8PgP9/" +
  "AAAAAAAAwANwHv7/////////////////PwAAfwAAAAAOAADA////////wP//AAAAAAAAgAPwA/7/////////////////HwCAPwAA" +
  "AAABAAAA/P//////8///AwAAAAAAfAfg8f//////////////////HwAAPwAAAAAAAACA/P//////4///DwAAAAAAPA/8////////" +
  "/////////////wUADwAAAAAAAAAA8f//////4///DwAAAAAAPD///////////////////////wcABwAAAAAAAAAA8P//////7///" +
  "DwAAAAAAhJ///////////////////////w0AAwAAAAAAAAAA8P//////////CQAAAAAAAOf//////////////////////w2AAAAA" +
  "AAAAAAAA4P////////8xLAAAAAAAAPj//////////////////////w0AAAAAAAAAAAAAgP7///////8PPgAAAAAAAP//////////" +
  "/////////////wQAAAAAAAAAAAAAAP////////8HXgAAAAAAAP7/////////////////////fwQAAAAAAAAAAAAAAP////////+P" +
  "AAAAAAAAAPz//////f//////////////PwQAAAAAAAAAAAAAAP////////9/AAAAAAAAAPj////j/v//////////////HwAAAAAA" +
  "AAAAAAAAAP////////8dAAAAAAAAAPj/+f8B/P//////////////DwQAAAAAAAAAAAAAAP///////z8EAAAAAAAA+P/H8/8A8P//" +
  "////////////Bx4AAAAAAAAAAAAAgP///////x8AAAAAAAAA+H+Aw/8A4P////////////9/AA8AAAAAAAAAAAAAAP///////x8A" +
  "AAAAAAAA+H8Ajv/x4f////////////8/AAAAAAAAAAAAAAAAAP///////wcAAAAAAAAA+B8wmN///////////////98fAAMAAAAA" +
  "AAAAAAAAAP///////wMAAAAAAAAA+A8wEMf//////////////2cOAAMAAAAAAAAAAAAAAP7/////fwEAAAAAAAAA+A8AEI7/////" +
  "/////////wMOgAEAAAAAAAAAAAAAAPz//////wAAAAAAAAAA+AcABob//////////////zcYgAEAAAAAAAAAAAAAAPz//////wAA" +
  "AAAAAAAAwOB/AAAz/////////////x888AEAAAAAAAAAAAAAAPj//////wAAAAAAAAAAQPh/ABAg/////////////w88/gEAAAAA" +
  "AAAAAAAAAPD/////fwAAAAAAAAAA4P9/AAAA/////////////w+AHwAAAAAAAAAAAAAAAMD/////HwAAAAAAAAAA8P9/AACA////" +
  "/////////x/gAwAAAAAAAAAAAAAAAID/////DwAAAAAAAAAA+P//BweA/////////////x/AAAAAAAAAAAAAAAAAAID/////BwAA" +
  "AAAAAAAA/P//D3/M/////////////z9AAAAAAAAAAAAAAAAAAAD7////BwAAAAAAAAAA/P///////////////////z8AAAAAAAAA" +
  "AAAAAAAAAAD2/58HBgAAAAAAAAAA/P///////8///////////z8AAAAAAAAAAAAAAAAAAAD0/w8ADgAAAAAAAAAA/v///////5//" +
  "/////////x8AAAAAAAAAAAAAAAAAAADu/wcADgAAAAAAAACA//////8//x///////////x8AAAAAAAAAAAAAAAAAAADY/wcADAAA" +
  "AAAAAADA//////8//z/k/////////w8AAAAAAAAAAAAAAAAAAACQ/wcACAAAAAAAAADg//////9//r/Q/////////w8AAAAAAAAA" +
  "AAAAAAAAAAAw/wcAAAAAAAAAAADg//////9//v8cgP///////yMAAAAAAAAAAAAAAAAAAABA/gMAAAAAAAAAAADw/////////P9/" +
  "AP///////zEAAAAAAAAAAAAAAAAAAAAA/AMAHwAAAAAAAAD4////////+P//AP7/////fxAAAAAAAAAAAAAAAAAAAAAA+AcccAAA" +
  "AAAAAAD4////////+f9/APz/H///DwAAAAAAAAAAAAAAAAAAAAAA/AcewAMAAAAAAADw////////8f9/AOD/B/5/AAAAAAAAAAAA" +
  "AAAAAQAAAAAA+A8eAHgAAAAAAAD4////////4/8/AOD/Af4/BgAAAAAAAAAAAAAAAAAAAAAA8N8PQPwCAAAAAADw////////4/8f" +
  "AOD/APw/AiAAAAAAAAAAAAAAAAAAAAAAgP8PAAAAAAAAAADw////////x/8HAOB/APx/ADAAAAAAAAAAAAAAAAAAAAAAAP4PAABA" +
  "AAAAAAD4////////h/8BAOA/AOz/ADAAAAAAAAAAAAAAAAAAAAAAAIj/AAAAAAAAAAD4////////z/8AAMAPAMD/ATAAAAAAAAAA" +
  "AAAAAAAAAAAAAAD/AQAAAAAAAAD4////////nx8AAMAPAMD/ASAAAAAAAAAAAAAAAAAAAAAAAAD8AQAAAAAAAAD4/////////wcA" +
  "AMAPAMD/AbAAAAAAAAAAAAAAAAAAAAAAAADgARAAAAAAAAD4/////////wAAAIAPAMD+AaAAAAAAAAAAAAAAAAAAAAAAAADAAEwA" +
  "AAAAAADw////////f2AAAAAPAMD4AUACAAAAAAAAAAAAAAAAAAAAAADAAf9TAAAAAADg/////////38AAAAPAED4AIAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAMe9/AAAAAADA/////////38AAAAXAMAgAAQAAAAAAAAAAAAAAAAAAAAAAAAA7v//AAAAAACA/////////z8A" +
  "AAASAMAAAIAHAAAAAAAAAAAAAAAAAAAAAAAAyP//AQAAAAAA/////////z8AAAAwAIAAAEAHAAAAAAAAAAAAAAAAAAAAAAAAwP//" +
  "AwAAAAAA/v///////x8AAAAwAAADAAMDAAAAAAAAAAAAAAAAAAAAAAAAwP//fwAAAAAA/A/+/////x8AAAAAABgHAAcAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAwP///wAAAAAAEAD8/////w8AAAAAADAPwAMAAAAAAAAAAAAAAAAAAAAAAAAAgP///wEAAAAAAADA/////wcA" +
  "AAAAAGAO4AMAAAAAAAAAAAAAAAAAAAAAAAAAwP///wEAAAAAAADA/////wMAAAAAAMAM+AMAAAAAAAAAAAAAAAAAAAAAAAAA4P//" +
  "/wMAAAAAAADg/////wEAAAAAAIAL/gMIAAAAAAAAAAAAAAAAAAAAAAAA8P///wMAAAAAAADg////fwAAAAAAAIAH/vMIAAAAAAAA" +
  "AAAAAAAAAAAAAAAB+P///x8AAAAAAADg////PwAAAAAAAAAP/guIAwAAAAAAAAAAAAAAAAAAAAAA+P///38AAAAAAADg////PwAA" +
  "AAAAAAAf/DmAEwAAAAAAAAAAAAAAAAAAAAAA+P////8BAAAAAADA////HwAAAAAAAAA+/DkA8wEAAAAAAAAAAAAAAAAAAAAA+P//" +
  "//8fAAAAAACA////DwAAAAAAAAA80Hhk/g8AAAAAAAAAAAAAAAAAAAAA+P////8/AAAAAAAA////BwAAAAAAAAA4AHgA+B8YAAAA" +
  "AAAAAAAAAAAAAAAA+P//////AQAAAAAA////BwAAAAAAAAAwAAAAwD8OAAAAAAAAAAAAAAAAAAAA+P//////AQAAAAAA////DwAA" +
  "AAAAAADAAAAAhH+AAAAAAAAAAAAAAAAAAAAA8P//////AQAAAAAA/v//DwAAAAAAAACAPwAAwH8AAAAAAAAAAAAAAAAAAAAA4P//" +
  "////AQAAAAAA/v//DwAAAAAAAAAA+LIHQM8AAgAAAAAAAAAAAAAAAAAA4P//////AAAAAAAA/v//DwAAAAAAAAAAAAABAIADEAAA" +
  "AAAAAAAAAAAAAAAAwP//////AAAAAAAA/v//DwAAAAAAAAAAAIAAAAAGAAAAAAAAAAAAAAAAAAAAgP////9/AAAAAAAA/P//HwAA" +
  "AAAAAAAAAABAAQQAAAAAAAAAAAAAAAAAAAAAgP////8/AAAAAAAA/v//HyAAAAAAAAAAAACAHwQAAAAAAAAAAAAAAAAAAAAAAP//" +
  "//8fAAAAAAAA////HzAAAAAAAAAAAADADw4AAAAAAAAAAAAAAAAAAAAAAP////8fAAAAAAAA////HzAAAAAAAAAAAADuDx4AAAAA" +
  "AAAAAAAAAAAAAAAAAP7///8fAAAAAAAA////H3gAAAAAAAAAAAD+Dz4AAAAAAAAAAAAAAAAAAAAAAPj///8fAAAAAAAA////Dz8A" +
  "AAAAAAAAAID/Pz4AABAAAAAAAAAAAAAAAAAAAOD///8fAAAAAACA////Az8AAAAAAAAAAMD//z8AAAAAAAAAAAAAAAAAAAAAAOD/" +
  "//8fAAAAAAAA////AR8AAAAAAAAAAMD//38AAAAAAAAAAAAAAAAAAAAAAMD///8PAAAAAAAA/v9/AB8AAAAAAAAAAOD//38AAAAA" +
  "AAAAAAAAAAAAAAAAAMD///8PAAAAAAAA/v9/AB8AAAAAAAAAAP7///8BAAAAAAAAAAAAAAAAAAAAAMD///8HAAAAAAAA/P9/gA8A" +
  "AAAAAAAAgP////8BAAIAAAAAAAAAAAAAAAAAAMD///8DAAAAAAAA/P//gA8AAAAAAAAAwP////8HAAAAAAAAAAAAAAAAAAAAAOD/" +
  "/38AAAAAAAAA/P//gA8AAAAAAAAAwP////8HAAAAAAAAAAAAAAAAAAAAAOD//x8AAAAAAAAA/P9/AAcAAAAAAAAA4P////8PAAAA" +
  "AAAAAAAAAAAAAAAAAOD//w8AAAAAAAAA+P8fAAIAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAOD//w8AAAAAAAAA+P8fAAAA" +
  "AAAAAAAA4P////8fAAAAAAAAAAAAAAAAAAAAAOD//w8AAAAAAAAA+P8fAAAAAAAAAAAAwP////8fAAAAAAAAAAAAAAAAAAAAAOD/" +
  "/wcAAAAAAAAA8P8PAAAAAAAAAAAAwP////8/AAAAAAAAAAAAAAAAAAAAAPD//wMAAAAAAAAA4P8HAAAAAAAAAAAAgP////8/AAAA" +
  "AAAAAAAAAAAAAAAAAPD//wMAAAAAAAAA4P8HAAAAAAAAAAAAgP////8fAAAAAAAAAAAAAAAAAAAAAPD//wAAAAAAAAAAwP8DAAAA" +
  "AAAAAAAAgP////8fAAAAAAAAAAAAAAAAAAAAAPD//wAAAAAAAAAAwP8BAAAAAAAAAAAAgP8H/P8PAAAAAAAAAAAAAAAAAAAAAPD/" +
  "fwAAAAAAAAAAwH8AAAAAAAAAAAAAgP8A+P8PAAAAAAAAAAAAAAAAAAAAAPD/PwAAAAAAAAAAgAMAAAAAAAAAAAAAgAcA6P8HAAAA" +
  "AAAAAAAAAAAAAAAAAPj/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgP8DAAACAAAAAAAAAAAAAAAAAPj/BwAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAP8DAAAEAAAAAAAAAAAAAAAAAPz/BwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8DAAAIAAAAAAAAAAAAAAAAAPz/" +
  "AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGwAAAA8AAAAAAAAAAAAAAAAAPg/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc" +
  "AAAAAAAAAAAAAAAAAPw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAPwHAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAOABAAAPAAAAAAAAAAAAAAAAAPwfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAIADAAAAAAAAAAAAAAAAAPgH" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAOABAAAAAAAAAAAAAAAAAPgHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAA" +
  "AAAAAAAAAAAAAAAAAPwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAP4BAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAP4DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4B" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAwAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANgA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAHAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "EgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAIAP" +
  "AAAAgP//fIDH/wEAAAAAAAAAAAAAAAAAAAAAAIAGAAAAAAAAAAAAAAAAAP7/PwDA/////////z8AAAAAAAAAAAAAAAAAAAAAAAAG" +
  "AAAAAAAAAAAAAAAg4P///wP8//////////9HAAAAAAAAAAAAAAAAAAAAADA/AAAAAAAAAAAAAADg+f///wH/////////////DwAA" +
  "AAAAAAAAAAAAAAAAAGI/AAAAAAAAAAB/f0L///////H/////////////3wcAAAAAAAAAAAAAAAAAAP5+AAAAAAAA/v//////////" +
  "//j//////////////38AAAAAAAAAAAAAAAcAAED+AAAAAACA////////////f////////////////z8AAAAAAAAAAAYA4P//ef//" +
  "AAAAAADw/////////////////////////////wcAAAAAAAAQ8P4TgP////8/AAAAAAD8/////////////////////////////wEA" +
  "AAAAAPD///////////8PAAAAAPD/////////////////////////////PwAAAAAAoP3//////////38AAAAAwP//////////////" +
  "////////////////fwAAAADAv////////////wcAAAAA/P///////////////////////////////wQAAAAA////////////P4AA" +
  "APwA/////////////////////////////////wQAAAAf8P///////////yADAP4Bw///////////////////////////////DwAA" +
  "AAAAwP///////////xDgwH8A/v//////////////////////////////DwAAAACA//////////////8DAAD8////////////////" +
  "////////////////PwAAAAAA/P////////////8f+P///////////////////////////////////wMAAP7/////////////////" +
  "//////////////////////////////////////8B/w//////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////" +
  "////////////////////////////////////////////////////////////////////////////////////////////////////";
